# Generated by Django 3.2.5 on 2022-09-06 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('AR_ID', models.AutoField(primary_key=True, serialize=False)),
                ('AR_DESIGNATION', models.CharField(max_length=50, unique=True)),
                ('AR_FAMILLE', models.CharField(max_length=50)),
                ('AR_PU_DEF', models.FloatField(default=0)),
                ('AR_STOCK_REEL', models.IntegerField(default=0)),
                ('AR_CODE', models.CharField(default='yaz', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('CL_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CL_NOM', models.CharField(max_length=100, unique=True)),
                ('CL_ADR', models.TextField(max_length=255)),
                ('CL_TEL', models.CharField(max_length=14)),
                ('CL_MAIL', models.CharField(max_length=100)),
                ('CL_RC', models.CharField(max_length=15)),
                ('CL_AI', models.CharField(max_length=15)),
                ('CL_NIF', models.CharField(max_length=15)),
                ('CL_CODE', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FicheCode',
            fields=[
                ('FIC_ID', models.AutoField(primary_key=True, serialize=False)),
                ('FIC_DESIGNATION', models.CharField(max_length=50, unique=True)),
                ('FIC_CODE', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('FO_ID', models.AutoField(primary_key=True, serialize=False)),
                ('FO_NOM', models.CharField(max_length=100, unique=True)),
                ('FO_ADR', models.TextField(max_length=255)),
                ('FO_TEL', models.CharField(max_length=14)),
                ('FO_MAIL', models.CharField(max_length=100)),
                ('FO_RC', models.CharField(max_length=15)),
                ('FO_AI', models.CharField(max_length=15)),
                ('FO_NIF', models.CharField(max_length=15)),
                ('FO_CODE', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeFrais',
            fields=[
                ('FRT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('FRT_NAME', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('FR_ID', models.AutoField(primary_key=True, serialize=False)),
                ('FR_DESIGNATION', models.TextField(max_length=255)),
                ('FR_MONTANT', models.FloatField(max_length=10)),
                ('FR_DATE', models.DateField()),
                ('FR_CODE', models.IntegerField()),
                ('FR_CODE_REF', models.TextField(default='FR_****', max_length=10, unique=True)),
                ('FR_TYPE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typefrais')),
            ],
        ),
        migrations.CreateModel(
            name='AchatLigne',
            fields=[
                ('ACHLIG_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ACHLIG_ID_ACHENT', models.IntegerField()),
                ('ACHLIG_QTY', models.IntegerField()),
                ('ACHLIG_PU', models.FloatField()),
                ('ACHLIG_REM', models.FloatField()),
                ('ACHLIG_ID_ART', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article')),
            ],
        ),
        migrations.CreateModel(
            name='AchatEntete',
            fields=[
                ('ACHENT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ACHENT_DOC', models.CharField(max_length=10, unique=True)),
                ('ACHENT_DATE', models.DateField(null=True)),
                ('ACHENT_CODE', models.IntegerField()),
                ('ACHENT_ID_FOURN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fournisseur')),
            ],
        ),
    ]
