# Generated by Django 3.2.5 on 2023-01-18 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('FAM_ID', models.AutoField(primary_key=True, serialize=False)),
                ('FAM_DES', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VenteLigne',
            fields=[
                ('VNTLIG_ID', models.AutoField(primary_key=True, serialize=False)),
                ('VNTLIG_ID_VNTENT', models.IntegerField()),
                ('VNTLIG_QTY', models.IntegerField()),
                ('VNTLIG_PU', models.FloatField()),
                ('VNTLIG_REM', models.FloatField()),
                ('VNTLIG_ID_ART', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article')),
            ],
        ),
        migrations.CreateModel(
            name='VenteEntete',
            fields=[
                ('VNTENT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('VNTENT_DOC', models.CharField(max_length=10, unique=True)),
                ('VNTENT_DATE', models.DateField(null=True)),
                ('VNTENT_CODE', models.IntegerField()),
                ('VNTENT_ID_CLIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
        ),
    ]
