# Generated by Django 3.2.5 on 2023-01-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230120_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='CL_CODE_CHAR',
            field=models.CharField(default='clold', max_length=5),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='FO_CODE_CHAR',
            field=models.CharField(default='foold', max_length=5),
        ),
        migrations.AlterField(
            model_name='achatentete',
            name='ACHENT_DOC',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='frais',
            name='FR_CODE_REF',
            field=models.TextField(default='FR_****', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='venteentete',
            name='VNTENT_DOC',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
